# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QSpacerItem, QStackedWidget, QStatusBar,
    QWidget)
import userUiRescources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        icon = QIcon(QIcon.fromTheme(u"emblem-shared"))
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.verticalSpacerTop = QSpacerItem(0, 15, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.verticalSpacerTop, 0, 1, 1, 1)

        self.horizontalSpacerLeft = QSpacerItem(15, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacerLeft, 4, 0, 1, 1)

        self.verticalSpacerBottom = QSpacerItem(0, 15, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.verticalSpacerBottom, 6, 1, 1, 1)

        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setFrameShape(QFrame.Shape.NoFrame)
        self.mainPage = QWidget()
        self.mainPage.setObjectName(u"mainPage")
        self.gridLayout_2 = QGridLayout(self.mainPage)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.frame = QFrame(self.mainPage)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QSize(1200, 350))
        self.frame.setFrameShape(QFrame.Shape.Box)
        self.frame.setFrameShadow(QFrame.Shadow.Plain)
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.takeCarPushButton = QPushButton(self.frame)
        self.takeCarPushButton.setObjectName(u"takeCarPushButton")
        font = QFont()
        font.setPointSize(42)
        font.setBold(True)
        self.takeCarPushButton.setFont(font)
        self.takeCarPushButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.takeCarPushButton.setToolTipDuration(3000)
        self.takeCarPushButton.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(140, 51, 85);")
        self.takeCarPushButton.setIconSize(QSize(42, 42))
        self.takeCarPushButton.setAutoDefault(False)

        self.horizontalLayout_2.addWidget(self.takeCarPushButton)

        self.horizontalSpacer = QSpacerItem(60, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.returnCarPushButton = QPushButton(self.frame)
        self.returnCarPushButton.setObjectName(u"returnCarPushButton")
        self.returnCarPushButton.setFont(font)
        self.returnCarPushButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.returnCarPushButton.setToolTipDuration(3000)
        self.returnCarPushButton.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(140, 51, 85);")
        self.returnCarPushButton.setIconSize(QSize(42, 42))

        self.horizontalLayout_2.addWidget(self.returnCarPushButton)


        self.gridLayout_2.addWidget(self.frame, 4, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(0, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.verticalSpacer, 2, 0, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(0, 15, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.verticalSpacer_2, 5, 0, 1, 1)

        self.statusFrame = QFrame(self.mainPage)
        self.statusFrame.setObjectName(u"statusFrame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.statusFrame.sizePolicy().hasHeightForWidth())
        self.statusFrame.setSizePolicy(sizePolicy1)
        self.statusFrame.setMaximumSize(QSize(1200, 1000))
        self.statusFrame.setFrameShape(QFrame.Shape.Box)
        self.statusFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.statusFrame.setLineWidth(1)
        self.gridLayout_3 = QGridLayout(self.statusFrame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.frame_3 = QFrame(self.statusFrame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.Shape.Box)
        self.frame_3.setFrameShadow(QFrame.Shadow.Plain)
        self.gridLayout_4 = QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.availablePlainTextEdit_2 = QPlainTextEdit(self.frame_3)
        self.availablePlainTextEdit_2.setObjectName(u"availablePlainTextEdit_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.availablePlainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.availablePlainTextEdit_2.setSizePolicy(sizePolicy2)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.availablePlainTextEdit_2.setFont(font1)
        self.availablePlainTextEdit_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.availablePlainTextEdit_2.setFrameShape(QFrame.Shape.NoFrame)
        self.availablePlainTextEdit_2.setFrameShadow(QFrame.Shadow.Plain)
        self.availablePlainTextEdit_2.setLineWidth(4)
        self.availablePlainTextEdit_2.setMidLineWidth(0)
        self.availablePlainTextEdit_2.setReadOnly(True)
        self.availablePlainTextEdit_2.setBackgroundVisible(False)

        self.gridLayout_4.addWidget(self.availablePlainTextEdit_2, 1, 0, 1, 1)

        self.availableLabel_2 = QLabel(self.frame_3)
        self.availableLabel_2.setObjectName(u"availableLabel_2")
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        self.availableLabel_2.setFont(font2)
        self.availableLabel_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.availableLabel_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.availableLabel_2, 0, 0, 1, 1)

        self.inUsePlainTextEdit_2 = QPlainTextEdit(self.frame_3)
        self.inUsePlainTextEdit_2.setObjectName(u"inUsePlainTextEdit_2")
        sizePolicy2.setHeightForWidth(self.inUsePlainTextEdit_2.sizePolicy().hasHeightForWidth())
        self.inUsePlainTextEdit_2.setSizePolicy(sizePolicy2)
        self.inUsePlainTextEdit_2.setFont(font1)
        self.inUsePlainTextEdit_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.inUsePlainTextEdit_2.setFrameShape(QFrame.Shape.NoFrame)
        self.inUsePlainTextEdit_2.setFrameShadow(QFrame.Shadow.Plain)
        self.inUsePlainTextEdit_2.setLineWidth(8)
        self.inUsePlainTextEdit_2.setReadOnly(True)

        self.gridLayout_4.addWidget(self.inUsePlainTextEdit_2, 1, 3, 1, 1)

        self.inUseLabel_2 = QLabel(self.frame_3)
        self.inUseLabel_2.setObjectName(u"inUseLabel_2")
        self.inUseLabel_2.setFont(font2)
        self.inUseLabel_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.inUseLabel_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_4.addWidget(self.inUseLabel_2, 0, 3, 1, 1)

        self.line_2 = QFrame(self.frame_3)
        self.line_2.setObjectName(u"line_2")
        sizePolicy1.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy1)
        self.line_2.setMaximumSize(QSize(3, 760))
        self.line_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.line_2.setFrameShadow(QFrame.Shadow.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QFrame.Shape.VLine)

        self.gridLayout_4.addWidget(self.line_2, 1, 2, 1, 1)


        self.gridLayout_3.addWidget(self.frame_3, 3, 1, 1, 1)

        self.statusLabel = QLabel(self.statusFrame)
        self.statusLabel.setObjectName(u"statusLabel")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy3)
        self.statusLabel.setMaximumSize(QSize(1200, 100))
        font3 = QFont()
        font3.setPointSize(36)
        font3.setBold(True)
        self.statusLabel.setFont(font3)
        self.statusLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.statusLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_3.addWidget(self.statusLabel, 1, 1, 1, 1)

        self.verticalSpacer_5 = QSpacerItem(0, 15, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout_3.addItem(self.verticalSpacer_5, 2, 1, 1, 1)


        self.gridLayout_2.addWidget(self.statusFrame, 9, 0, 1, 1)

        self.verticalSpacer_4 = QSpacerItem(0, 15, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.verticalSpacer_4, 11, 0, 1, 1)

        self.stackedWidget.addWidget(self.mainPage)
        self.lendPage = QWidget()
        self.lendPage.setObjectName(u"lendPage")
        self.reasonComboBox = QComboBox(self.lendPage)
        self.reasonComboBox.setObjectName(u"reasonComboBox")
        self.reasonComboBox.setGeometry(QRect(640, 180, 491, 61))
        font4 = QFont()
        font4.setPointSize(28)
        font4.setBold(True)
        self.reasonComboBox.setFont(font4)
        self.reasonComboBox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.reasonComboBox.setStyleSheet(u"background-color: rgb(255, 255, 127);\n"
"color: rgb(32, 75, 70);")
        self.ssnLineEdit = QLineEdit(self.lendPage)
        self.ssnLineEdit.setObjectName(u"ssnLineEdit")
        self.ssnLineEdit.setEnabled(True)
        self.ssnLineEdit.setGeometry(QRect(180, 700, 191, 31))
        font5 = QFont()
        font5.setPointSize(18)
        self.ssnLineEdit.setFont(font5)
        self.ssnLineEdit.setStyleSheet(u"background-color: rgb(255, 255, 127);\n"
"color: rgb(32, 75, 70);")
        self.ssnLineEdit.setEchoMode(QLineEdit.EchoMode.Password)
        self.ssnLineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ssnLineEdit.setClearButtonEnabled(True)
        self.lenderNameLabel = QLabel(self.lendPage)
        self.lenderNameLabel.setObjectName(u"lenderNameLabel")
        self.lenderNameLabel.setGeometry(QRect(70, 610, 431, 71))
        font6 = QFont()
        font6.setFamilies([u"Trebuchet MS"])
        font6.setPointSize(24)
        font6.setBold(True)
        self.lenderNameLabel.setFont(font6)
        self.lenderNameLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lenderNameLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lenderPictureLabel = QLabel(self.lendPage)
        self.lenderPictureLabel.setObjectName(u"lenderPictureLabel")
        self.lenderPictureLabel.setEnabled(True)
        self.lenderPictureLabel.setGeometry(QRect(170, 360, 211, 231))
        self.lenderPictureLabel.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.lenderPictureLabel.setPixmap(QPixmap(u":/pictures/uiPictures/Teacher.png"))
        self.lenderPictureLabel.setScaledContents(False)
        self.keyBarcodeLineEdit = QLineEdit(self.lendPage)
        self.keyBarcodeLineEdit.setObjectName(u"keyBarcodeLineEdit")
        self.keyBarcodeLineEdit.setEnabled(True)
        self.keyBarcodeLineEdit.setGeometry(QRect(620, 600, 181, 51))
        self.keyBarcodeLineEdit.setFont(font6)
        self.keyBarcodeLineEdit.setStyleSheet(u"background-color: rgb(208, 208, 208);")
        self.keyBarcodeLineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.keyBarcodeLineEdit.setClearButtonEnabled(True)
        self.registerPlateBGLabel = QLabel(self.lendPage)
        self.registerPlateBGLabel.setObjectName(u"registerPlateBGLabel")
        self.registerPlateBGLabel.setGeometry(QRect(580, 590, 241, 71))
        self.registerPlateBGLabel.setPixmap(QPixmap(u":/pictures/uiPictures/plateBGPicture.png"))
        self.registerPlateBGLabel.setScaledContents(True)
        self.keyPictureLabel = QLabel(self.lendPage)
        self.keyPictureLabel.setObjectName(u"keyPictureLabel")
        self.keyPictureLabel.setEnabled(True)
        self.keyPictureLabel.setGeometry(QRect(590, 430, 201, 141))
        self.keyPictureLabel.setPixmap(QPixmap(u":/pictures/uiPictures/keys.png"))
        self.keyPictureLabel.setScaledContents(True)
        self.carInfoLabel = QLabel(self.lendPage)
        self.carInfoLabel.setObjectName(u"carInfoLabel")
        self.carInfoLabel.setGeometry(QRect(980, 630, 181, 51))
        font7 = QFont()
        font7.setPointSize(14)
        self.carInfoLabel.setFont(font7)
        self.carInfoLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.carInfoLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.vehiclePictureLabel = QLabel(self.lendPage)
        self.vehiclePictureLabel.setObjectName(u"vehiclePictureLabel")
        self.vehiclePictureLabel.setGeometry(QRect(920, 420, 291, 191))
        self.vehiclePictureLabel.setPixmap(QPixmap(u"uiPictures/OXZ915.png"))
        self.vehiclePictureLabel.setScaledContents(True)
        self.calendarLabel = QLabel(self.lendPage)
        self.calendarLabel.setObjectName(u"calendarLabel")
        self.calendarLabel.setGeometry(QRect(1350, 480, 31, 51))
        self.calendarLabel.setPixmap(QPixmap(u":/pictures/uiPictures/calendar.png"))
        self.calendarLabel.setScaledContents(True)
        self.dateLabel = QLabel(self.lendPage)
        self.dateLabel.setObjectName(u"dateLabel")
        self.dateLabel.setEnabled(True)
        self.dateLabel.setGeometry(QRect(1390, 490, 221, 41))
        font8 = QFont()
        font8.setPointSize(28)
        self.dateLabel.setFont(font8)
        self.dateLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.clockLabel = QLabel(self.lendPage)
        self.clockLabel.setObjectName(u"clockLabel")
        self.clockLabel.setGeometry(QRect(1350, 560, 41, 41))
        self.clockLabel.setPixmap(QPixmap(u":/pictures/uiPictures/clock.png"))
        self.clockLabel.setScaledContents(True)
        self.timeLabel = QLabel(self.lendPage)
        self.timeLabel.setObjectName(u"timeLabel")
        self.timeLabel.setEnabled(True)
        self.timeLabel.setGeometry(QRect(1410, 560, 111, 41))
        self.timeLabel.setFont(font8)
        self.timeLabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.stackedWidget.addWidget(self.lendPage)
        self.registerPlateBGLabel.raise_()
        self.reasonComboBox.raise_()
        self.ssnLineEdit.raise_()
        self.lenderNameLabel.raise_()
        self.lenderPictureLabel.raise_()
        self.keyBarcodeLineEdit.raise_()
        self.keyPictureLabel.raise_()
        self.carInfoLabel.raise_()
        self.vehiclePictureLabel.raise_()
        self.calendarLabel.raise_()
        self.dateLabel.raise_()
        self.clockLabel.raise_()
        self.timeLabel.raise_()
        self.returnPage = QWidget()
        self.returnPage.setObjectName(u"returnPage")
        self.keyReturnBarcodeLineEdit = QLineEdit(self.returnPage)
        self.keyReturnBarcodeLineEdit.setObjectName(u"keyReturnBarcodeLineEdit")
        self.keyReturnBarcodeLineEdit.setEnabled(True)
        self.keyReturnBarcodeLineEdit.setGeometry(QRect(870, 680, 181, 50))
        self.keyReturnBarcodeLineEdit.setFont(font6)
        self.keyReturnBarcodeLineEdit.setStyleSheet(u"background-color: rgb(208, 208, 208);")
        self.keyReturnBarcodeLineEdit.setFrame(False)
        self.keyReturnBarcodeLineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.keyReturnBarcodeLineEdit.setClearButtonEnabled(True)
        self.registerPlateBGReturnLabel = QLabel(self.returnPage)
        self.registerPlateBGReturnLabel.setObjectName(u"registerPlateBGReturnLabel")
        self.registerPlateBGReturnLabel.setGeometry(QRect(830, 670, 241, 71))
        self.registerPlateBGReturnLabel.setPixmap(QPixmap(u":/pictures/uiPictures/plateBGPicture.png"))
        self.registerPlateBGReturnLabel.setScaledContents(True)
        self.keyPictureReturnLabel = QLabel(self.returnPage)
        self.keyPictureReturnLabel.setObjectName(u"keyPictureReturnLabel")
        self.keyPictureReturnLabel.setEnabled(True)
        self.keyPictureReturnLabel.setGeometry(QRect(840, 520, 201, 141))
        self.keyPictureReturnLabel.setPixmap(QPixmap(u":/pictures/uiPictures/keys.png"))
        self.keyPictureReturnLabel.setScaledContents(True)
        self.stackedWidget.addWidget(self.returnPage)

        self.gridLayout.addWidget(self.stackedWidget, 4, 1, 1, 1)

        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.Shape.Box)
        self.frame_4.setFrameShadow(QFrame.Shadow.Plain)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_4)

        self.okPushButton = QPushButton(self.frame_4)
        self.okPushButton.setObjectName(u"okPushButton")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.okPushButton.sizePolicy().hasHeightForWidth())
        self.okPushButton.setSizePolicy(sizePolicy4)
        self.okPushButton.setMinimumSize(QSize(250, 55))
        self.okPushButton.setMaximumSize(QSize(250, 55))
        font9 = QFont()
        font9.setPointSize(24)
        font9.setBold(True)
        self.okPushButton.setFont(font9)
        self.okPushButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.okPushButton.setStyleSheet(u"background-color: rgb(140, 51, 85);\n"
"color: rgb(255, 255, 255);")
        self.okPushButton.setIconSize(QSize(32, 32))

        self.horizontalLayout_4.addWidget(self.okPushButton)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalSpacer_3 = QSpacerItem(40, 0, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_3)

        self.goBackPushButton = QPushButton(self.frame_4)
        self.goBackPushButton.setObjectName(u"goBackPushButton")
        sizePolicy4.setHeightForWidth(self.goBackPushButton.sizePolicy().hasHeightForWidth())
        self.goBackPushButton.setSizePolicy(sizePolicy4)
        self.goBackPushButton.setMinimumSize(QSize(250, 55))
        self.goBackPushButton.setMaximumSize(QSize(250, 55))
        self.goBackPushButton.setFont(font9)
        self.goBackPushButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.goBackPushButton.setStyleSheet(u"background-color: rgb(140, 51, 85);\n"
"color: rgb(255, 255, 255);")
        icon1 = QIcon()
        icon1.addFile(u":/pictures/uiPictures/back.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.goBackPushButton.setIcon(icon1)
        self.goBackPushButton.setIconSize(QSize(32, 32))

        self.horizontalLayout_3.addWidget(self.goBackPushButton)


        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)


        self.gridLayout.addWidget(self.frame_4, 5, 1, 1, 1)

        self.horizontalSpacerRight = QSpacerItem(15, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacerRight, 4, 3, 1, 1)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy1.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy1)
        self.frame_2.setMaximumSize(QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QFrame.Shape.Box)
        self.frame_2.setFrameShadow(QFrame.Shadow.Plain)
        self.horizontalLayout = QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.soundCheckBox = QCheckBox(self.frame_2)
        self.soundCheckBox.setObjectName(u"soundCheckBox")
        self.soundCheckBox.setMaximumSize(QSize(80, 80))
        font10 = QFont()
        font10.setPointSize(9)
        self.soundCheckBox.setFont(font10)
        self.soundCheckBox.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.soundCheckBox.setAutoFillBackground(False)
        self.soundCheckBox.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"\n"
"")
        icon2 = QIcon(QIcon.fromTheme(u"audio-volume-medium"))
        self.soundCheckBox.setIcon(icon2)
        self.soundCheckBox.setIconSize(QSize(64, 64))

        self.horizontalLayout.addWidget(self.soundCheckBox)

        self.logoLabel_3 = QLabel(self.frame_2)
        self.logoLabel_3.setObjectName(u"logoLabel_3")
        sizePolicy1.setHeightForWidth(self.logoLabel_3.sizePolicy().hasHeightForWidth())
        self.logoLabel_3.setSizePolicy(sizePolicy1)
        self.logoLabel_3.setMinimumSize(QSize(0, 0))
        self.logoLabel_3.setMaximumSize(QSize(80, 80))
        self.logoLabel_3.setPixmap(QPixmap(u"uiPictures/Raseko-logo-pysty_NEGA.png"))
        self.logoLabel_3.setScaledContents(True)

        self.horizontalLayout.addWidget(self.logoLabel_3)


        self.gridLayout.addWidget(self.frame_2, 2, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1920, 33))
        self.menubar.setStyleSheet(u"background-color: rgb(0, 33, 72);\n"
"color: rgb(255, 255, 255);")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setFont(font10)
        self.statusbar.setToolTipDuration(-1)
        self.statusbar.setStyleSheet(u"background-color: rgb(243, 89, 148);")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Rasekon ajoneuvojen lainaus", None))
#if QT_CONFIG(tooltip)
        self.takeCarPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt;\">Avaa auton lainausikkunan</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.takeCarPushButton.setText(QCoreApplication.translate("MainWindow", u"LAINAA", None))
#if QT_CONFIG(tooltip)
        self.returnCarPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt;\">Avaa auton palautusikkunan</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.returnCarPushButton.setText(QCoreApplication.translate("MainWindow", u"PALAUTA", None))
        self.availablePlainTextEdit_2.setPlainText("")
        self.availableLabel_2.setText(QCoreApplication.translate("MainWindow", u"VAPAANA", None))
        self.inUsePlainTextEdit_2.setPlainText(QCoreApplication.translate("MainWindow", u"AM-15 Renault Megane 5 henkil\u00f6\u00e4", None))
        self.inUseLabel_2.setText(QCoreApplication.translate("MainWindow", u"AJOSSA", None))
        self.statusLabel.setText(QCoreApplication.translate("MainWindow", u"Tila", None))
        self.reasonComboBox.setCurrentText("")
        self.reasonComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Ajon tarkoitus", None))
        self.ssnLineEdit.setText("")
        self.ssnLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue ajokortti", None))
        self.lenderNameLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaajan nimi", None))
        self.lenderPictureLabel.setText("")
        self.keyBarcodeLineEdit.setText("")
        self.keyBarcodeLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avain", None))
        self.registerPlateBGLabel.setText("")
        self.keyPictureLabel.setText("")
        self.carInfoLabel.setText(QCoreApplication.translate("MainWindow", u"Merkki ja malli", None))
        self.vehiclePictureLabel.setText("")
        self.calendarLabel.setText("")
        self.dateLabel.setText("")
        self.clockLabel.setText("")
        self.timeLabel.setText("")
        self.keyReturnBarcodeLineEdit.setText("")
        self.keyReturnBarcodeLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avain", None))
        self.registerPlateBGReturnLabel.setText("")
        self.keyPictureReturnLabel.setText("")
#if QT_CONFIG(tooltip)
        self.okPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt;\">Tallentaa tiedot ajop\u00e4iv\u00e4kirjaan</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.okPushButton.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.goBackPushButton.setText(QCoreApplication.translate("MainWindow", u"KUMOA", None))
        self.soundCheckBox.setText("")
        self.logoLabel_3.setText("")
    # retranslateUi

